"""
AI Engine Module
Integrates with Google Gemini AI for natural language risk explanations.
"""

import google.generativeai as genai
import json

# Configure Gemini API
API_KEY = "AIzaSyBn6HxMhLxbjHr-bHw67lJeOUPMukWE54g"
genai.configure(api_key=API_KEY)

# Define Professional System Instructions for Expert Risk Analysis
SYSTEM_PROMPT = """You are an expert **maritime risk intelligence analyst** working for a marine insurance company.

Your role is to interpret voyage risk signals and generate clear explanations for insurance underwriters.

You analyze vessel risk using the following factors:

• Weather severity (storms, high winds, wave height)
• Piracy or maritime security incidents along the route
• Port congestion and operational delays
• Vessel behavioural anomalies such as route deviation or abnormal speed

Your task is NOT to calculate the risk score.
The risk score is already computed by the system.

Your job is to **explain the drivers behind the risk score** in simple professional language suitable for marine insurance analysts.

Guidelines:

1. Focus on the most important risk factors.
2. Use clear analytical language.
3. Keep explanations concise.
4. Avoid speculation or unnecessary technical jargon.
5. Limit explanations to **2–3 sentences maximum**.
6. If risk is low, briefly explain why the voyage appears safe.
7. If risk is medium or high, clearly identify the primary drivers of risk.

Tone:

Professional, analytical, and concise — similar to an insurance risk briefing.

Output format:

Return only the explanation text.
Do not include headings, bullet points, or formatting.
"""

def get_best_model():
    """
    Dynamically identifies the best available Gemini model that supports text generation.
    """
    try:
        # Priority order for preferred models
        preferred = ['gemini-1.5-flash', 'gemini-1.5-pro', 'gemini-2.0-flash', 'gemini-pro']
        
        available_models = [m.name for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]
        
        # Check for preferred models in the available list
        for p in preferred:
            # Check for name or models/name
            full_p = f"models/{p}" if not p.startswith('models/') else p
            if full_p in available_models or any(p in m for m in available_models):
                # Find the actual name from the list
                actual_name = next((m for m in available_models if p in m), full_p)
                return actual_name
        
        # Fallback to the first available model if none of the preferred are found
        return available_models[0] if available_models else 'gemini-pro'
        
    except Exception:
        return 'gemini-1.5-flash' # Generic fallback

def generate_ai_explanation(data: dict) -> str:
    """
    Calls Google Gemini AI to generate a risk explanation.
    """
    
    prompt = f"""
Vessel: {data['vessel']}
Weather Risk: {data['weather']}
Piracy Risk: {data['piracy']}
Port Congestion Risk: {data['congestion']}
Behaviour Risk: {data['behaviour']}
Total Voyage Risk: {data['total']}
"""

    try:
        model_name = get_best_model()
        
        model = genai.GenerativeModel(
            model_name=model_name,
            system_instruction=SYSTEM_PROMPT
        )
        
        response = model.generate_content(prompt)
        
        if response and response.text:
            return response.text.strip()
        else:
            return "No explanation generated by AI."
            
    except Exception as e:
        return f"Risk explanation unavailable (Gemini AI Error). Reason: {str(e)}"

if __name__ == "__main__":
    # Quick standalone test
    test_data = {
        "vessel": "Test Vessel",
        "weather": 0.8,
        "piracy": 0.6,
        "congestion": 0.5,
        "behaviour": 0.7,
        "total": 0.67
    }
    print("Testing Dynamic Gemini Integration...")
    print(generate_ai_explanation(test_data))
